//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchEduSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int AdminId { get; set; }
        public string AdminName { get; set; }
        public string AdminGender { get; set; }
        public string AdminTelephone { get; set; }
        public string AdminEmail { get; set; }
        public string AdminPassword { get; set; }
    }
}
