//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchEduSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.courseandtopic = new HashSet<courseandtopic>();
        }
    
        public int courseId { get; set; }
        public string courseName { get; set; }
        public System.DateTime courseStartTime { get; set; }
        public string courseLogo { get; set; }
        public string courseDescription { get; set; }
        public string courseCode { get; set; }
        public float courseCredit { get; set; }
        public string courseLevel { get; set; }
        public string courseType { get; set; }
        public int courseDepartmentId { get; set; }
        public string courseDepartmentName { get; set; }
        public int coursePeriod { get; set; }
        public string courseFAQ { get; set; }
        public string courseGradingPolicy { get; set; }
        public string courseRequirements { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<courseandtopic> courseandtopic { get; set; }
        public virtual department department { get; set; }
    }
}
